Combining solve nonhydro stencils 14 to 28
C2SM/icon4py pull request #292
Opened 2023-10-16 13:36 UTC by nfarabullini

Fusion of stencils:

 - mo_math_gradients_grad_green_gauss_cell_dsl 
 - mo_solve_nonhydro_4th_order_divdamp 
 - mo_solve_nonhydro_stencil_16_fused_btraj_traj_o1 
 - mo_solve_nonhydro_stencil_17 
 - mo_solve_nonhydro_stencil_18
 - mo_solve_nonhydro_stencil_19 
 - mo_solve_nonhydro_stencil_20 
 - mo_solve_nonhydro_stencil_21 
 - mo_solve_nonhydro_stencil_22
 - mo_solve_nonhydro_stencil_23 
 - mo_solve_nonhydro_stencil_24 
 - mo_solve_nonhydro_stencil_25 
 - mo_solve_nonhydro_stencil_26
 - mo_solve_nonhydro_stencil_27 
 - mo_solve_nonhydro_stencil_28 

implementation into dycore granule, subsequent stencils edits and datatest implementations, renaming

2025-03-21 16:37 UTC, OngChia commented
cscs-ci run default

2025-03-24 10:17 UTC, OngChia commented
cscs-ci run default

2025-03-25 12:10 UTC, nfarabullini commented
cscs-ci run default

2025-03-27 09:32 UTC, OngChia commented
cscs-ci run default

2025-03-27 09:58 UTC, nfarabullini commented
cscs-ci run default

2025-03-27 10:09 UTC, OngChia commented
cscs-ci run default

2025-03-27 11:10 UTC, OngChia commented
cscs-ci run default

2025-03-27 12:37 UTC, OngChia commented
cscs-ci run default

2025-03-27 13:07 UTC, OngChia commented
cscs-ci run default

2025-03-27 13:55 UTC, OngChia commented
cscs-ci run default

2025-03-28 13:21 UTC, OngChia commented
cscs-ci run default

2025-03-28 16:28 UTC, OngChia commented
cscs-ci run default

2025-03-31 08:08 UTC, nfarabullini commented
cscs-ci run default

2025-03-31 09:07 UTC, OngChia commented
cscs-ci run default

2025-03-31 09:33 UTC, OngChia commented
cscs-ci run default

2025-03-31 11:03 UTC, OngChia commented
cscs-ci run default

2025-03-31 11:39 UTC, nfarabullini commented
cscs-ci run default

2025-03-31 11:44 UTC, OngChia commented
cscs-ci run default

2025-04-01 08:46 UTC, nfarabullini commented
cscs-ci run default

2025-04-02 07:35 UTC, halungge requested changes

2025-04-02 07:35 UTC, halungge commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/stencils/compute_edge_diagnostics_for_dycore_and_update_vn.py
> +    TAYLOR_HYDRO_gradp_method: gtx.int32,
Could we not use the `FrozenNamespace` trick here to not have to pass these constant values (see `saturation_adjustment.py`)

2025-04-02 07:35 UTC, halungge commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/stencils/compute_edge_diagnostics_for_dycore_and_update_vn.py
> +    COMBINED_divdamp_order: gtx.int32,
same here.

2025-04-02 08:10 UTC, nfarabullini commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/stencils/compute_edge_diagnostics_for_dycore_and_update_vn.py
> +    TAYLOR_HYDRO_gradp_method: gtx.int32,
this makes a lot of sense

2025-04-02 08:19 UTC, nfarabullini commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/dycore_states.py
> +    horizontal_mask_for_3d_divdamp: fa.EdgeField[float]
this is a question for @OngChia

2025-04-02 08:22 UTC, nfarabullini commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/stencils/compute_edge_diagnostics_for_dycore_and_update_vn.py
this is a question for @OngChia

2025-04-02 11:36 UTC, muellch approved these changes
Awesome!
One gigantic stencil done!

2025-04-02 11:36 UTC, muellch commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/stencils/compute_edge_diagnostics_for_dycore_and_update_vn.py
> +        where(
I guess all domain `where` need to be substituted with `concat_where` now.

2025-04-02 11:41 UTC, nfarabullini commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/stencils/compute_edge_diagnostics_for_dycore_and_update_vn.py
> +        where(
I realized this just now and have the changes locally, will push soon. but thanks!

2025-04-02 14:06 UTC, nfarabullini commented
cscs-ci run default

2025-04-03 07:26 UTC, nfarabullini commented
cscs-ci run default

2025-04-03 09:30 UTC, OngChia commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/stencils/compute_edge_diagnostics_for_dycore_and_update_vn.py
Totally agreed. The in_corrector_step and in_predictor_step have nothing to do with computations inside. I will remove them.

2025-04-03 12:37 UTC, OngChia commented on model/atmosphere/dycore/tests/dycore_stencil_tests/test_apply_divergence_damping_and_update_vn_in_corrector_step.py
> +        fourth_order_divdamp_factor = 0.004
Thanks for noting that. Not all branches are tested now. All computations are executed except that either `_apply_weighted_2nd_and_4th_order_divergence_damping` and `_apply_4th_order_divergence_damping` is executed depending on the parameters. if second_order_divdamp_factor <= 4 * fourth_order_divdamp_factor, I found that it only depends on whether `limited_area` is True or False. I decreased `second_order_divdamp_factor` to 0.012 (it is safer to decrease it instead of increasing `fourth_order_divdamp_factor` because computation may become unstable and NaN appear) added a params in the pytest.fixture for the `input_data` function to test both cases.

I also just found out that it is indeed also true for the datatest. `is_iau_active` is False for all experiments and _add_analysis_increments_to_vn is never called. This condition
```
if (
    (divdamp_order == divergence_damp_order.COMBINED)
    & (second_order_divdamp_factor <= (4.0 * fourth_order_divdamp_factor))
    & limited_area
)
```
is also never met and `_apply_weighted_2nd_and_4th_order_divergence_damping` is never called. We may need to turn them on in our experiments in the future.

2025-04-03 14:13 UTC, OngChia commented
cscs-ci run default

2025-04-08 07:33 UTC, nfarabullini commented
cscs-ci run default

2025-04-15 12:32 UTC, nfarabullini commented
cscs-ci run dace

2025-04-15 13:37 UTC, nfarabullini commented
cscs-ci run dace

2025-04-22 07:38 UTC, nfarabullini commented
cscs-ci run dace

2025-04-22 08:15 UTC, nfarabullini commented
cscs-ci run dace

2025-04-22 13:25 UTC, nfarabullini commented
cscs-ci run default

2025-04-22 13:53 UTC, nfarabullini commented
cscs-ci run default

2025-04-22 14:35 UTC, nfarabullini commented
cscs-ci run default

2025-04-22 17:26 UTC, nfarabullini commented
cscs-ci run default

2025-04-22 20:22 UTC, nfarabullini commented
cscs-ci run default

2025-04-23 09:19 UTC, halungge requested changes
Looks good, some small changes,  and the issue with `RhoThetaAdvectionType` that I mentioned (if the condition is take such from ICON should even be removed there... )

2025-04-23 09:19 UTC, halungge commented on tools/tests/py2fgen/wrappers/test_dycore_wrapper.py
> +    vn_incr = test_utils.array_to_array_info(
Is this on always initialized with zero in a dycore run? or is there some input from previous timesteps and it should be read from the serializer?

2025-04-23 09:19 UTC, halungge commented on model/common/tests/metric_tests/test_metric_scalars.py
See remark above,  in metric_scalars.py

2025-04-23 09:19 UTC, halungge commented on model/atmosphere/dycore/tests/dycore_tests/test_solve_nonhydro.py
> +    # TODO Fix REGIONAL
Can this be removed?

2025-04-23 09:19 UTC, halungge commented on model/atmosphere/dycore/tests/dycore_tests/test_solve_nonhydro.py
> +    # stencil 31 - TODO savepoint value starts differing from 0.0 at 1688 which is a n edge boundary
Is this still an issue, or has the TODO been fixed?

1688 is `start_index(lateral_boundary_3)` for **cells** not edges.

2025-04-23 09:29 UTC, nfarabullini commented on model/atmosphere/dycore/tests/dycore_stencil_tests/test_compute_theta_rho_face_values_and_pressure_gradient_and_update_vn.py
> +def sten_16_numpy(
@OngChia

2025-04-23 09:33 UTC, nfarabullini commented on model/atmosphere/dycore/tests/dycore_stencil_tests/test_compute_theta_rho_face_values_and_pressure_gradient_and_update_vn.py
> +        vertical_end: gtx.int32,
I need `horizontal_start` and `horizontal_end` in the gt4py program, which means that I have to set those variables in the `input_data` dict, but if I remove them in the reference, it outputs this error: 
```
    def _test_validation(
        self,
        grid: base.BaseGrid,
        backend: gtx_backend.Backend,
        connectivities_as_numpy: dict,
        input_data: dict,
    ):
        if self.MARKERS is not None:
            apply_markers(self.MARKERS, grid, backend)
    
        connectivities = connectivities_as_numpy
>       reference_outputs = self.reference(
            connectivities,
            **{k: v.asnumpy() if isinstance(v, gtx.Field) else v for k, v in input_data.items()},
        )
E       TypeError: TestComputeThetaRhoPressureGradientAndUpdateVn.reference() got an unexpected keyword argument 'horizontal_start'
```

2025-04-23 09:47 UTC, nfarabullini commented on tools/tests/py2fgen/wrappers/test_dycore_wrapper.py
> +    vn_incr = test_utils.array_to_array_info(
@OngChia

2025-04-23 09:47 UTC, nfarabullini commented on model/common/tests/metric_tests/test_metric_scalars.py
@OngChia

2025-04-23 09:48 UTC, nfarabullini commented on model/atmosphere/dycore/tests/dycore_tests/test_solve_nonhydro.py
> +    # stencil 31 - TODO savepoint value starts differing from 0.0 at 1688 which is a n edge boundary
@OngChia

2025-04-23 09:53 UTC, nfarabullini commented
cscs-ci run default

2025-04-23 12:02 UTC, halungge commented on model/atmosphere/dycore/tests/dycore_stencil_tests/test_compute_theta_rho_face_values_and_pressure_gradient_and_update_vn.py
> +        vertical_end: gtx.int32,
yes, you need the `**kwargs` if you remove them.

2025-04-23 12:06 UTC, nfarabullini commented
cscs-ci run default

2025-04-23 13:08 UTC, OngChia commented on model/atmosphere/dycore/tests/dycore_tests/test_solve_nonhydro.py
> +    # stencil 31 - TODO savepoint value starts differing from 0.0 at 1688 which is a n edge boundary
Absolutely not an issue. Not sure why it is written as 1688, maybe a typo. `z_vn_avg` is a local variables. It is initialized to zero in icon4py. So, it is not a problem that it differs from the serialized data outside of the bounds (`solve_nonhydro._start_edge_lateral_boundary_level_5`). I remove it.

2025-04-23 13:42 UTC, OngChia commented on tools/tests/py2fgen/wrappers/test_dycore_wrapper.py
> +    vn_incr = test_utils.array_to_array_info(
It is nonzero in the case of IAU type data assimilation. However, in our two experiments (the meteoSwiss regional and aquaplanet simulations), is_iau_active is `False` and `vn_incr` is not used in the dycore, and `vn_incr` is not serialized. So, I simply initialize it to zero.

2025-04-23 14:09 UTC, OngChia commented
cscs-ci run default

2025-04-24 10:36 UTC, halungge commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/solve_nonhydro.py
> +            )
Use the backend dependent import form data_allocation.py instead of numpy. It should be somthing like:
```suggestion
xp = data_alloc.import_array_ns(self.backend)
self.starting_vertical_index_for_3d_divdamp = xp.min(
              xp.where(self._metric_state_nonhydro.scaling_factor_for_3d_divdamp.ndarray > 0.0)
            )
```

2025-04-24 10:43 UTC, nfarabullini commented
cscs-ci run default

2025-04-24 10:44 UTC, nfarabullini commented
cscs-ci run default

2025-04-24 11:31 UTC, halungge approved these changes

2025-04-24 12:00 UTC, merged