Gpu datatest
C2SM/icon4py pull request #553
Opened 2024-09-19 12:33 UTC by OngChia

Enable single-node GPU run for the Jablonowski-WIlliamson test on R2B4 grid and all datatests for the Timeloop.
1. Change np to xp in `serialbox_utils.py`.
2. Change asnumpy() to ndarray in `test_timeloop.py` and `jablownski_williamson.py` and `driver/utils.py`
3. Split `predictor_stencils_7_8_9` to two stencils to avoid illegal memory access when running on gpu.
4. Add a new field `exner_dyn_incr_lastsubstep` in class `DiagnosticStateNonHydro` as the output argument for the stencil `update_dynamical_exner_time_increment` because this stencil originally updates the input argument `exner_dyn_incr`.

2024-09-19 13:34 UTC, OngChia commented
cscs-ci run default

2024-09-19 14:25 UTC, halungge requested changes
Some renaming, for the numpy.ma parts you might pick changes from this [PR](https://github.com/C2SM/icon4py/pull/554)

2024-09-19 14:25 UTC, halungge commented on model/common/src/icon4py/model/common/decomposition/definitions.py
>          self._global_index[dim] = masked_global_index
I guess that won't work. I don't now what happens with the mask if you do that and we need it that mask later. But indeed cupy does not implement the numpy's masked_array interface. We would have to do a simple hand made implementation which should be enough for what we need.   I'll open a fix for that.

2024-09-19 15:34 UTC, OngChia commented on model/driver/src/icon4py/model/driver/test_cases/jablonowski_williamson.py
> +# TODO (Chia Rui): Convert all numpy computations to cupy
Ah. Thanks. I forgot to delete it.

2024-09-19 18:31 UTC, OngChia commented
cscs-ci run default

2024-09-24 11:25 UTC, OngChia commented
cscs-ci run default

2024-09-24 11:25 UTC, OngChia commented
launch jenkins spack

2024-09-24 11:26 UTC, OngChia commented
cscs-ci run default

2024-09-24 11:26 UTC, OngChia commented
launch jenkins spack

2024-09-24 11:29 UTC, OngChia commented
cscs-ci run default

2024-09-24 11:29 UTC, OngChia commented
launch jenkins spack

2024-09-25 18:50 UTC, OngChia commented
cscs-ci run default

2024-09-25 18:50 UTC, OngChia commented
launch jenkins spack

2024-12-12 17:06 UTC, closed without merging