first set of change
C2SM/icon4py pull request #575
Opened 2024-10-24 12:54 UTC by nfarabullini

2024-10-24 12:54 UTC, nfarabullini commented
cscs-ci run default

2024-10-24 12:54 UTC, nfarabullini commented
launch jenkins spack

2024-10-24 13:51 UTC, nfarabullini commented
cscs-ci run default

2024-10-24 13:51 UTC, nfarabullini commented
launch jenkins spack

2024-10-24 16:10 UTC, nfarabullini commented
cscs-ci run default

2024-10-24 16:10 UTC, nfarabullini commented
launch jenkins spack

2024-10-25 08:42 UTC, nfarabullini commented
launch jenkins spack

2024-10-25 08:42 UTC, nfarabullini commented
cscs-ci run default

2024-10-25 11:18 UTC, nfarabullini commented
launch jenkins spack

2024-10-28 07:40 UTC, nfarabullini commented
cscs-ci run default

2024-10-28 07:40 UTC, nfarabullini commented
launch jenkins spack

2024-10-28 08:20 UTC, nfarabullini commented
cscs-ci run default

2024-10-28 08:20 UTC, nfarabullini commented
launch jenkins spack

2024-10-28 14:31 UTC, nfarabullini commented
cscs-ci run default

2024-10-28 14:31 UTC, nfarabullini commented
launch jenkins spack

2024-10-29 12:10 UTC, nfarabullini commented
launch jenkins spack

2024-10-29 12:10 UTC, nfarabullini commented
cscs-ci run default

2024-10-29 13:16 UTC, nfarabullini commented
launch jenkins spack

2024-10-29 13:52 UTC, nfarabullini commented
launch jenkins spack

2024-10-30 07:50 UTC, nfarabullini commented
cscs-ci run default

2024-10-30 07:50 UTC, nfarabullini commented
launch jenkins spack

2024-10-30 07:52 UTC, nfarabullini commented
cscs-ci run default

2024-10-30 08:28 UTC, nfarabullini commented
cscs-ci run default

2024-10-30 08:29 UTC, nfarabullini commented
launch jenkins spack

2024-10-30 10:35 UTC, nfarabullini commented
cscs-ci run default

2024-10-30 10:36 UTC, nfarabullini commented
launch jenkins spack

2024-10-30 14:13 UTC, nfarabullini commented
cscs-ci run default

2024-10-30 14:13 UTC, nfarabullini commented
launch jenkins spack

2024-10-30 14:47 UTC, nfarabullini commented
cscs-ci run default

2024-10-30 14:47 UTC, nfarabullini commented
launch jenkins spack

2024-10-30 15:38 UTC, nfarabullini commented
cscs-ci run default

2024-10-30 15:38 UTC, nfarabullini commented
launch jenkins spack

2024-10-30 16:06 UTC, nfarabullini commented
cscs-ci run default

2024-10-30 16:06 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 08:51 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 08:51 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 09:33 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 09:33 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 09:47 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 09:47 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 12:59 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 12:59 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 13:00 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 13:01 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 14:13 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 14:13 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 14:52 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 15:25 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 15:25 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 16:42 UTC, nfarabullini commented
launch jenkins spack

2024-10-31 16:42 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 17:10 UTC, nfarabullini commented
cscs-ci run default

2024-10-31 17:10 UTC, nfarabullini commented
launch jenkins spack

2024-11-01 08:39 UTC, nfarabullini commented
cscs-ci run default

2024-11-01 08:40 UTC, nfarabullini commented
launch jenkins spack

2024-11-01 09:06 UTC, nfarabullini commented
launch jenkins spack

2024-11-01 09:06 UTC, nfarabullini commented
cscs-ci run default

2024-11-01 09:30 UTC, nfarabullini commented
cscs-ci run default

2024-11-01 09:30 UTC, nfarabullini commented
launch jenkins spack

2024-11-01 09:41 UTC, nfarabullini commented
launch jenkins spack

2024-11-01 09:42 UTC, nfarabullini commented
cscs-ci run default

2024-11-01 10:55 UTC, nfarabullini commented
launch jenkins spack

2024-11-01 11:36 UTC, nfarabullini commented
cscs-ci run default

2024-11-01 11:36 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 08:29 UTC, nfarabullini commented
cscs-ci run default

2024-11-26 08:29 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 09:42 UTC, nfarabullini commented
cscs-ci run default

2024-11-26 09:42 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 10:02 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 10:02 UTC, nfarabullini commented
cscs-ci run default

2024-11-26 12:03 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 12:03 UTC, nfarabullini commented
cscs-ci run default

2024-11-26 12:31 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 12:56 UTC, nfarabullini commented
cscs-ci run default

2024-11-26 13:18 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 13:57 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 13:57 UTC, nfarabullini commented
cscs-ci run default

2024-11-26 14:17 UTC, nfarabullini commented
cscs-ci run default

2024-11-26 14:17 UTC, nfarabullini commented
launch jenkins spack

2024-11-26 14:55 UTC, nfarabullini commented
cscs-ci run default

2024-11-26 14:55 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 07:44 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 07:44 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 08:32 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 08:32 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 09:01 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 09:24 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 09:24 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 09:45 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 09:45 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 10:07 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 10:07 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 11:21 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 11:21 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 12:34 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 12:34 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 12:58 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 13:44 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 13:44 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 14:06 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 14:06 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 14:07 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 14:08 UTC, nfarabullini commented
cscs-ci run default

2024-11-27 14:08 UTC, nfarabullini commented
launch jenkins spack

2024-11-27 15:07 UTC, nfarabullini commented
cscs-ci run default

2024-11-28 13:52 UTC, nfarabullini commented
cscs-ci run default

2024-11-28 13:54 UTC, nfarabullini commented
cscs-ci run default

2024-11-28 14:21 UTC, nfarabullini commented
cscs-ci run default

2024-11-28 14:52 UTC, nfarabullini commented
cscs-ci run default

2024-11-28 15:53 UTC, nfarabullini commented
cscs-ci run default

2024-11-28 16:26 UTC, nfarabullini commented
cscs-ci run default

2024-11-28 17:30 UTC, nfarabullini commented
cscs-ci run default

2024-11-29 08:12 UTC, nfarabullini commented
cscs-ci run default

2024-11-29 08:12 UTC, nfarabullini commented
launch jenkins spack

2024-11-29 11:54 UTC, nfarabullini commented
cscs-ci run default

2024-11-29 11:54 UTC, nfarabullini commented
launch jenkins spack

2024-11-29 12:23 UTC, nfarabullini commented on model/atmosphere/diffusion/tests/diffusion_tests/mpi_tests/test_parallel_diffusion.py
> +    if dace_orchestration is None:
```suggestion
    if "dace" not in backend.name.lower():
```

2024-11-29 12:23 UTC, nfarabullini commented on model/atmosphere/diffusion/tests/diffusion_tests/test_diffusion.py
> +    if not dace_orchestration:
```suggestion
    if "dace" not in backend.name.lower():
```

2024-11-29 12:23 UTC, nfarabullini commented on model/common/src/icon4py/model/common/settings.py
> +import numpy as xp
```suggestion
import numpy as np
```

2024-11-29 12:34 UTC, nfarabullini commented
cscs-ci run default

2024-11-29 12:34 UTC, nfarabullini commented
launch jenkins spack

2024-12-01 20:51 UTC, halungge requested changes
Tests look all good. A couple of fixes, mostly.


- In `tools.py2fgen` use the `xp` everywhere as before just the location where you import it from has changed, it does not longer import from  the xp icon4py.model.common` but from its own `icon4pytools.py2fgen.settings`
- where appropriate use a  NDArray = Union[cupy.ndarray, numpy.ndarray] in the type annotations.

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/base.py
> +            np.asarray(self.connectivities[dim]),
Can you remove the `asarray` here all together? Does that work? We should allocate the connectivity arrays already on the right device such that the do not need to be transferred here.

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/geometry.py
> +import numpy as np
Can you add a TODO here that we check whether this works on GPU? You an put my name.
```suggestion
# TODO (@halungge ) test on GPU (NEP 18 ?) 
import numpy as np
```

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/refinement.py
> +def is_unordered_field(field: np.ndarray, dim: dims.Dimension) -> np.ndarray:
```suggestion
def is_unordered_field(field: NDArray, dim: dims.Dimension) -> NDArray:
```

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/refinement.py
> +    assert field.dtype in (np.int32, np.int64), f"not an integer type {field.dtype}"
```suggestion
    assert field.dtype in (gtx.int32, gtx.int64), f"not an integer type {field.dtype}"
```

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/refinement.py
> +    assert field.dtype in (np.int32, np.int64), f"not an integer type {field.dtype}"
```suggestion
    assert field.dtype in (gtx.int32, gtx.int64), f"not an integer type {field.dtype}"
```

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/refinement.py
> +def convert_to_unnested_refinement_values(field: np.ndarray, dim: dims.Dimension) -> np.ndarray:
```suggestion
def convert_to_unnested_refinement_values(field: NDArray, dim: dims.Dimension) -> NDArray:
```

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/vertical.py
> +        cls, vct_a: np.ndarray, top_moist_threshold: float, nshift_total: int = 0
```suggestion
        cls, vct_a: NDArray, top_moist_threshold: float, nshift_total: int = 0
```

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/vertical.py
> +    def _determine_damping_height_index(cls, vct_a: np.ndarray, damping_height: float) -> gtx.int32:
```suggestion
    def _determine_damping_height_index(cls, vct_a: NDArray, damping_height: float) -> gtx.int32:
```

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/grid/vertical.py
> +        cls, vct_a: np.ndarray, flat_height: float
```suggestion
        cls, vct_a: NDArray, flat_height: float
```

2024-12-01 20:51 UTC, halungge commented on model/common/src/icon4py/model/common/test_utils/helpers.py
> +    return as_field(
```suggestion
    domain = {d: _shape(grid, dims, extend) for d in dims}
    return gtx.zeros(domain, dtype=dtype, allocator=backend)
```
should work.

2024-12-02 08:29 UTC, kotsaloscv requested changes
LGTM

2024-12-02 08:29 UTC, kotsaloscv commented on model/atmosphere/diffusion/tests/diffusion_tests/mpi_tests/test_parallel_diffusion.py
>          raise pytest.skip("This test is only executed for `--dace-orchestration=True`.")
Could you please remove this option from the pytest configuration?
This is not needed anymore.
Thank you!

2024-12-02 08:29 UTC, kotsaloscv commented on model/common/src/icon4py/model/common/test_utils/pytest_config.py
>          parser.addoption(
This is not needed anymore, i.e. `--dace-orchestration `

2024-12-02 10:31 UTC, nfarabullini commented
cscs-ci run default

2024-12-02 11:14 UTC, nfarabullini commented
cscs-ci run default

2024-12-02 11:56 UTC, nfarabullini commented
cscs-ci run default

2024-12-02 12:38 UTC, nfarabullini commented
cscs-ci run default

2024-12-03 08:40 UTC, nfarabullini commented
cscs-ci run default

2024-12-03 09:42 UTC, kotsaloscv approved these changes

2024-12-03 10:06 UTC, nfarabullini commented on model/atmosphere/dycore/src/icon4py/model/atmosphere/dycore/velocity_advection.py
> +            domain=(dims.KDim,), data=(np.any(self.cfl_clipping.ndarray, 0)), dtype=bool
`cfl_clipping` has dimensions `[CellDim, KDim]` but we cannot return a KDim only field in gt4py

2024-12-03 10:07 UTC, nfarabullini commented
launch jenkins spack

2024-12-03 10:38 UTC, nfarabullini commented
cscs-ci run default

2024-12-03 11:29 UTC, nfarabullini commented
launch jenkins spack

2024-12-03 14:33 UTC, nfarabullini commented
cscs-ci run default

2024-12-03 14:34 UTC, nfarabullini commented
launch jenkins spack

2024-12-03 15:33 UTC, nfarabullini commented
cscs-ci run default

2024-12-03 15:34 UTC, nfarabullini commented
launch jenkins spack

2024-12-04 09:13 UTC, halungge reviewed
Some small things still:
- Can you fix the import for `NDArray` everywhere: don't import the TypeAlias directly but import the module? 
- In tools you don't need the `NDArray`: there we do the xp import as before so we can use xp.ndarray as type annotations.
There are some places where a `isinstance` check needs to explicitly check for numpy.ndarray.

2024-12-04 09:13 UTC, halungge commented on tools/src/icon4pytools/py2fgen/wrappers/common.py
> +    cell_starts: NDArray,
you have the `xp` import as before in `wrappers.common`: 
You can use `xp.ndarray` as before, then you dont need to import another module (gt4py_field_allocation.py) from the model here, which is preferable.

2024-12-04 09:13 UTC, halungge commented on tools/src/icon4pytools/py2fgen/wrappers/common.py
> +    c2e2c0 = xp.column_stack((xp.asarray(range(c2e2c.shape[0])), c2e2c.ndarray))
the connectvities that are used here are `xp.ndarray` not fields.You don need the extra .ndarray.
```suggestion
    c2e2c0 = xp.column_stack((xp.asarray(range(c2e2c.shape[0])), c2e2c))
```

2024-12-04 09:13 UTC, halungge commented on tools/src/icon4pytools/py2fgen/wrappers/common.py
> +    c_glb_index: NDArray,
```suggestion
    c_glb_index: xp.ndarray,
```
Same here you have the xp import from settings here.

2024-12-04 09:13 UTC, halungge commented on tools/src/icon4pytools/py2fgen/wrappers/dycore_wrapper.py
> +from icon4py.model.common.utils import PredictorCorrectorPair, TimeStepPair
```suggestion
from icon4py.model.common import utils import as common_utils
```

2024-12-04 09:13 UTC, halungge commented on tools/src/icon4pytools/py2fgen/wrappers/dycore_wrapper.py
> +        ddt_w_adv_pc=PredictorCorrectorPair(ddt_w_adv_ntl1, ddt_w_adv_ntl2),
```suggestion
        ddt_vn_apc_pc=common_utils.PredictorCorrectorPair(ddt_vn_apc_ntl1, ddt_vn_apc_ntl2),
        ddt_w_adv_pc=common_utils.PredictorCorrectorPair(ddt_w_adv_ntl1, ddt_w_adv_ntl2),
```

2024-12-04 09:13 UTC, halungge commented on tools/src/icon4pytools/py2fgen/wrappers/dycore_wrapper.py
> +    prognostic_states = TimeStepPair(prognostic_state_nnow, prognostic_state_nnew)
```suggestion
    prognostic_states = common_utils.TimeStepPair(prognostic_state_nnow, prognostic_state_nnew)
```

2024-12-04 10:14 UTC, nfarabullini commented
cscs-ci run default

2024-12-04 10:14 UTC, nfarabullini commented
launch jenkins spack

2024-12-04 10:47 UTC, nfarabullini commented
cscs-ci run default

2024-12-05 15:04 UTC, nfarabullini commented
launch jenkins spack

2024-12-05 15:04 UTC, nfarabullini commented
cscs-ci run default

2024-12-05 15:52 UTC, nfarabullini commented
cscs-ci run default

2024-12-05 16:41 UTC, nfarabullini commented
cscs-ci run default

2024-12-05 17:10 UTC, nfarabullini commented
cscs-ci run default

2024-12-06 08:38 UTC, nfarabullini commented
cscs-ci run default

2024-12-06 09:17 UTC, nfarabullini commented
launch jenkins spack

2024-12-06 09:23 UTC, nfarabullini commented
cscs-ci run default

2024-12-06 12:05 UTC, nfarabullini commented
launch jenkins spack

2024-12-06 12:05 UTC, nfarabullini commented
cscs-ci run default

2024-12-06 12:13 UTC, halungge reviewed
Can you rerun without those `hasattr` calls in `grid/icon.py` and `grid/base.py` Otherwise I think it is good to go, the rest we can fine tune in another PR.

2024-12-06 12:13 UTC, halungge commented on model/common/src/icon4py/model/common/grid/base.py
> +                d: k.ndarray.astype(gtx.int32) if hasattr(k, "ndarray") else k.astype(gtx.int32)
Can you still remove and rerun without the `hasattr`? 
```suggestion
               self.connectivities.update({d: k.astype(gtx.int32) for d, k in connectivity.items()})
```

2024-12-06 12:13 UTC, halungge commented on model/common/src/icon4py/model/common/grid/icon.py
> +        start_indices: field_alloc.NDArray,
According to Chia Rui those must be on CPU, you could keep a `np.ndarray` here.

2024-12-06 12:13 UTC, halungge commented on model/common/src/icon4py/model/common/grid/icon.py
> +            else start_indices.astype(gtx.int32)
Same as above: Can you drop the if branch and rerun. 

```suggestion
start_indices.astype(gtx.int32)
```

2024-12-06 12:13 UTC, halungge commented on model/common/src/icon4py/model/common/grid/icon.py
> +            else end_indices.astype(gtx.int32)
```suggestion
            end_indices.astype(gtx.int32)
```

2024-12-06 12:54 UTC, nfarabullini commented
cscs-ci run default

2024-12-06 14:25 UTC, halungge commented
cscs-ci run default

2024-12-06 14:46 UTC, nfarabullini commented
launch jenkins spack

2024-12-06 15:20 UTC, halungge approved these changes

2024-12-06 16:59 UTC, merged