Add convergence study in horizontal advection
C2SM/icon4py pull request #580
Opened 2024-10-31 10:58 UTC by dastrm

2026-07-10 15:49 UTC, msimberg commented
@dastrm is this something worth keeping open?

2026-07-11 16:25 UTC, dastrm commented
Yes, in fact this should have been merged a long time ago. Convergence studies represent an elegant form of verification.

2026-07-30 13:47 UTC, OngChia commented
@msimberg @dastrm 
Hi, I am updating this branch. I will move the initial condition to the place where we hold other initial conditions such as JW and warm bubble, and then run the convergence test from the driver as the first part of our effort to implement the scientific validation.

2026-08-03 01:13 UTC, OngChia commented
@dastrm 
What resolution did you use in your convergence test? Do you still keep the grids that you generated? If so, where can I get your grids? Is the reason that you first generated the tracer IC on vertices and derive the cell center value using second-order quadrature over a symmetric triangle to get a second-order accurate IC?
I am sorry in advance that I may have more questions coming up when I work through this PR. I sincerely appreciate your help, and I hope you won't mind answering them whenever you have time.

2026-08-08 08:58 UTC, dastrm commented
> @dastrm What resolution did you use in your convergence test? Do you still keep the grids that you generated? If so, where can I get your grids? Is the reason that you first generated the tracer IC on vertices and derive the cell center value using second-order quadrature over a symmetric triangle to get a second-order accurate IC? I am sorry in advance that I may have more questions coming up when I work through this PR. I sincerely appreciate your help, and I hope you won't mind answering them whenever you have time.

Hey Chia Rui, I trust you're doing well.

Unfortunately I don't have the five torus grids anymore. These test ran on my laptop and completed in a few minutes maximum. Therefore my best guess is somewhere between 1e4 and 1e5 cells, although you can probably adjust the resolution and tweak the convergence tolerances a bit.

Regarding the initial conditions, even with pure advection there are cases where the convergence is limited by the accuracy of the ICs. Remember that finite volume schemes model cell averages (one constant function per cell) instead of cell center values. To be on the safe side it is good practice to initialize the cell averages with a sufficiently high-order quadrature rule such that the test actually measures the accuracy of the scheme and not of the initial distribution. If I remember correctly this is exactly what is happening here. I used a higher-order quadrature rule for arbitrary triangles which makes use of the values on the vertices.

2026-08-08 20:06 UTC, OngChia commented
I am using torus grids with width and height 1km by 1km. The mean edge length is 100, 50, 25, 12.5, 6.25, 3.125, and 1.5625 m. The convergence (L1 norm) rate seems to be only first order. The initial condition is GAUSSIAN_2D. CFL number is 0.2. And the velocity field is constant with magnitude `(Lx, Ly)`, where Lx and Ly are domain length and height, respectively. The integration time is 0.5 s. I am going to investigate whether this is because I removed the part where the domain length and height are fixed when calculating the initial condition. But it is hard for me to believe that a slight difference in the domain size will have any significant impact on the convergence rate. Otherwise, if we need higher-order quadrature. @dastrm do you have any ideas why?
<img width="598" height="368" alt="image" src="https://github.com/user-attachments/assets/3b806327-d37b-4875-8a71-ded2b0bf48ca" />

2026-08-08 20:08 UTC, OngChia commented
When measuring the error with L_inf norm, the convergence rate is slightly worse.
<img width="761" height="464" alt="image" src="https://github.com/user-attachments/assets/e8817757-4a9d-450c-bcf2-5ca525e5a29b" />

2026-08-10 11:15 UTC, dastrm commented
> I am using torus grids with width and height 1km by 1km. The mean edge length is 100, 50, 25, 12.5, 6.25, 3.125, and 1.5625 m. The convergence (L1 norm) rate seems to be only first order. The initial condition is GAUSSIAN_2D. CFL number is 0.2. And the velocity field is constant with magnitude `(Lx, Ly)`, where Lx and Ly are domain length and height, respectively. The integration time is 0.5 s. I am going to investigate whether this is because I removed the part where the domain length and height are fixed when calculating the initial condition. But it is hard for me to believe that a slight difference in the domain size will have any significant impact on the convergence rate. Otherwise, if we need higher-order quadrature. @dastrm do you have any ideas why? <img alt="image" width="598" height="368" src="https://private-user-images.githubusercontent.com/93439630/633320601-3b806327-d37b-4875-8a71-ded2b0bf48ca.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODYzNTg4NTIsIm5iZiI6MTc4NjM1ODU1MiwicGF0aCI6Ii85MzQzOTYzMC82MzMzMjA2MDEtM2I4MDYzMjctZDM3Yi00ODc1LThhNzEtZGVkMmIwYmY0OGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODEwVDEwNDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZGIwODFiZTY5MzM0MGI4MDgwYzI2OTg0ZjBjNTBjMzI2NTc5ODc0MDczYjVhYjY0M2VjMjUzOWUzNDBmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.S5K_jh3361_vmeSzoU8CS-Fy4zxDPtudDLW7zvp2kOE">

First of all, the resolution looks good to me. You should be able to see the second-order accuracy with these grids, and moreover you would probably not even be able to tell the results apart from the `p = 2.0` line below an error of ~1e-2.

Now that we know what to expect, obviously something is fishy here. As always it could be anything, namely the scheme itself or the test setup. For now I'd assume the latter and start with plotting the initial conditions, the solution and maybe also the error to double-check that you're actually calculating what you think you are. A visual inspection could help you rule out trivial mistakes such as too large ICs that would introduce a significant kink in the solution due to the periodicity of the grid. Given that you have some kind of convergence in the infinity norm already, it may be only a small thing that needs adjustment.

2026-08-10 13:22 UTC, OngChia commented
@dastrm I still have no concrete evidence on what went wrong. Did you have a report on your horizontal convergence test? Could you send me the report of if there is one?

2026-08-10 16:25 UTC, OngChia commented
@dastrm Thanks for your hints!! It was really helpful to look at the plots. Good news is that the problems have been resolved. It was my fault after all. 1) Indeed the decay factor for the Gaussian shape was too large and a kink appears in the domain. 2.) I fixed the CFL number to compute dtime. However, the driver rounds off the number of time steps because the integration time is not an integer multiple of dtime. And I used the integration time to compute the reference solution. It then introduced a first-order error because the actual integration time is different from what I specified at the beginning. After fixing that, the convergence rate is correct.

2026-08-17 09:09 UTC, OngChia commented
cscs-ci run default;LEVELS=validation;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-08-17 10:30 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-08-17 13:14 UTC, nfarabullini requested changes

2026-08-17 13:14 UTC, nfarabullini commented on model/atmosphere/tracer_advection/src/icon4py/model/atmosphere/tracer_advection/tracer_advection_horizontal.py
> +class FirstOrderUpwind(FiniteVolume):
earlier you have `HorizontalAdvectionType.UPWIND_1ST_ORDER`, now `FirstOrderUpwind`. Can you choose one order of words?

2026-08-17 13:14 UTC, nfarabullini commented on model/atmosphere/tracer_advection/src/icon4py/model/atmosphere/tracer_advection/tracer_advection_horizontal.py
> +    """Class that does one horizontal first-order accurate upwind finite volume advection step."""
```suggestion
    """Perform one horizontal first-order accurate upwind finite volume advection step."""
```

2026-08-17 13:14 UTC, nfarabullini commented on model/atmosphere/tracer_advection/tests/tracer_advection/stencil_tests/test_compute_horizontal_tracer_flux_upwind.py
> +class TestComputeHorizontalTracerFluxUpwind(stencil_tests.StencilTest):
a new PR should be merged soon with stencil tests conventions: https://github.com/C2SM/icon4py/pull/1116/changes#diff-77c24472f3c343e888a4d4b3f782bcf75d4bf6b4caee6ac34e4ef622478bddea

Make sure this test is consistent

2026-08-17 13:14 UTC, nfarabullini commented on model/common/src/icon4py/model/common/config/config_io.py
> +    return time.RelativeTime(seconds=float(reltime_val))
why are you changing this type from int to float?

2026-08-17 13:14 UTC, nfarabullini commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_advection.py
> +    CONSTANT = 1
maybe you a different name than just `CONSTANT`, it's a broadly used term

2026-08-17 13:14 UTC, nfarabullini commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_advection.py
> +    nodes: data_alloc.NDArray,
This is an old thing, but we usually place all arrays first and then scalars

2026-08-17 13:14 UTC, nfarabullini commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_advection.py
> +
you don't return anything in this function?

2026-08-17 13:14 UTC, nfarabullini commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_vertical_advection.py
> +
VelocityField and TracerProfile are classes already defined in `model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_advection.py`
so redefining classes with the same name here will lead to confusion. How about, e.g. `VTracerProfile` and `HTracerProfile` for the other?

2026-08-17 13:14 UTC, nfarabullini commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_vertical_advection.py
> +
same for VelocityField and _compute_idealized_velocity_field

2026-08-17 13:14 UTC, nfarabullini commented on model/common/src/icon4py/model/common/states/adv_states.py
> +
use `tracer_advection`, not just `advection`. We had a PR a few weeks ago exactly tackling this different nomenclature as simply `advection` can be confused with velocity advection

2026-08-17 13:14 UTC, nfarabullini commented on model/driver/src/icon4py/model/driver/driver.py
> +        tracer_prep_adv: adv_states.AdvectionPrepAdvState | None,
same for all of these imports: `adv_states` --> `tracer_adv_states`
```suggestion
        tracer_prep_adv: tracer_adv_states.AdvectionPrepAdvState | None,
```

2026-08-17 13:14 UTC, nfarabullini commented on model/driver/tests/driver/integration_tests/test_initial_conditions.py
> +        adv_prep_adv_state=None,
adv prep adv?

2026-08-17 13:14 UTC, nfarabullini commented on model/driver/tests/driver/scientific_validation/linear_advection_tests.py
> +
please rename to specify which advection this is

2026-08-17 13:14 UTC, nfarabullini commented on model/common/src/icon4py/model/common/states/adv_states.py
> +
for reference: https://github.com/C2SM/icon4py/pull/1399

2026-08-17 13:14 UTC, nfarabullini commented on model/driver/tests/driver/unit_tests/test_driver_states.py
> +    "solve_nonhydro_enabled, with_adv_prep_adv_state",
why do you parametrize `solve_nonhydro_enabled` is it's always False? You can also define it directly inside the test

2026-08-18 08:27 UTC, nfarabullini commented
cscs-ci run default

2026-08-18 08:31 UTC, OngChia commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_advection.py
> +    CONSTANT = 1
Let me think a better name

2026-08-18 11:15 UTC, OngChia commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_advection.py
> +
Let me investigate

2026-08-18 11:16 UTC, OngChia commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_vertical_advection.py
> +
Okay!

2026-08-18 16:31 UTC, OngChia commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_advection.py
> +
I have renamed the function to `_fill_tracer_from_analytical_profile` and the argument tracer to `tracer_buffer` to clearly indicate we are filling some values into the array buffer.

2026-08-18 16:45 UTC, OngChia commented on model/atmosphere/tracer_advection/src/icon4py/model/atmosphere/tracer_advection/tracer_advection_horizontal.py
> +class FirstOrderUpwind(FiniteVolume):
I found out that David already named other classes in this order while the `HorizontalAdvectionType` in the other way round (for example, `SecondOrderMiura`, `LINEAR_2ND_ORDER` ). I think usually we first say the order of accuracy first and then the scheme's name. So, I will prefer this ordering. But, I need to modify other others too for consistency. For example, `MIURA_2ND_ORDER` -> `SECOND_ORDER_LINEAR_MIURA`, `PPM_3RD_ORDER` -> `THIRD_ORDER_PPM`. How do you think about these names?
Maybe @jcanton should also give some opinions.
I do not have opinions about the naming here.

2026-08-18 16:56 UTC, OngChia commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_advection.py
> +    CONSTANT = 1
I rename it to UNIFORM_XY.  So, something like `if velocity_field == VelocityField.UNIFORM_XY` looks more understandable to me that we have a uniform wind field in both x and y directions. Feel free to suggest any other names if you find this is not okay.

2026-08-18 17:11 UTC, OngChia commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_vertical_advection.py
> +
I added horizontal or vertical in front.

2026-08-19 14:18 UTC, OngChia commented on model/driver/tests/driver/integration_tests/test_initial_conditions.py
> +        adv_prep_adv_state=None,
Changed it to tracer_prep_adv

2026-08-20 09:16 UTC, nfarabullini commented on model/atmosphere/tracer_advection/src/icon4py/model/atmosphere/tracer_advection/tracer_advection_horizontal.py
> +class FirstOrderUpwind(FiniteVolume):
I'm fine with your preference

2026-08-20 11:27 UTC, nfarabullini commented on model/common/src/icon4py/model/common/states/prep_adv_states.py
> +
@OngChia can you also rename the file to include `tracer`?

2026-08-20 11:29 UTC, nfarabullini approved these changes

2026-08-24 09:40 UTC, msimberg reviewed
Some preliminary comments. Some of the testing comments may need a bit more discussion in person.

2026-08-24 09:40 UTC, msimberg commented on experiment_configs/linear_vertical_advection_box.yaml
> +geometry: {}
Just starting the review, but it feels like these should not be at the top level. Possibly somewhere closer to the testing module and closer to the experiment fixture definitions.

2026-08-24 09:40 UTC, msimberg commented on model/atmosphere/tracer_advection/src/icon4py/model/atmosphere/tracer_advection/tracer_advection_vertical.py
> +    Abstract base class for finite-volume vertical tracer advection schemes.
Not abstract base class? It has implementations?

2026-08-24 09:40 UTC, msimberg commented on model/common/src/icon4py/model/common/config/config_io.py
> +def unstructure_reltime(reltime: time.RelativeTime) -> float:
Just curious: what was the motivation for the changes in this file?

2026-08-24 09:40 UTC, msimberg commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_vertical_tracer_advection.py
> +    return data_alloc.array_namespace(w).max(data_alloc.array_namespace(w).abs(w))
Maybe add array_ns as a local variable. But also, there may be methods that you can use instead and do w.abs().max(). Not 100% sure if they exist, in which case that's obviously not an option...

2026-08-24 09:40 UTC, msimberg commented on model/common/src/icon4py/model/common/states/prep_adv_states.py
> +def initialize_tracer_prep_adv_state(
Nit: I think we can use prepare advection state generally instead of prep adv state (file names, classes, functions, etc.). But I know the short names already existed, so not a must to change in this PR.

2026-08-24 09:40 UTC, msimberg commented on model/common/tests/common/config/unit_tests/test_config_io.py
> +        ("300.0\n...\n", time.RelativeTime, time.RelativeTime(seconds=300)),
Related to other questions, why are these now floats?

2026-08-24 09:40 UTC, msimberg commented on model/driver/tests/driver/validation_tests/test_tracer_advection_convergence.py
> +# ICON4Py - ICON inspired code in Python and GT4Py
I still need to get a slightly better overview of this PR, but we should at the very least be calling this directory `somnething_tests` to be consistent with others, and so that they're easy to find and glob for testing. Simplest would likely be `validation_tests` to mirror `unit_tests` and `integration_tests`.

2026-08-24 09:40 UTC, msimberg commented on model/testing/src/icon4py/model/testing/fixtures/torus_grids.py
> +def generate_torus_grid(tmp_path_factory: pytest.TempPathFactory) -> Callable[..., pathlib.Path]:
I have some concerns about this setup.

How flexible do you need to be with different torus grids? On one hand I wonder if we can avoid creating the torus grid file at all, and only keep it in memory. I don't know if the grid generator has a documented API that doesn't create nc files. That'd be the cleanest if you really want to be able to easily generate new test cases on the fly. On the other hand, if you don't need the flexibility, I think it'd probably be worth sticking with the existing path of GridDescription and uploading pre-generated grids uploaded to the test data storage since it avoids divergence. I'm not saying either of these is strictly better, but should be considered. We can discuss more in person as well.

2026-08-24 09:40 UTC, msimberg commented on model/testing/src/icon4py/model/testing/config.py
> +)
It feels weird that this is overridable via an env var. Why is it?

2026-08-24 09:40 UTC, msimberg commented on model/testing/pyproject.toml
> +  "icon-grid-generator[netcdf]>=0.8.0",
The big question is if we want to have this as a hard dependency now. Nothing per-se against it, but wondering if we can avoid it. See other comment about the `generate_torus_grid` fixture as well.

2026-08-24 12:42 UTC, OngChia commented on model/common/src/icon4py/model/common/states/prep_adv_states.py
> +def initialize_tracer_prep_adv_state(
And I forgot to remove this file... There is another file `tracer_prep_adv_states.py` in the same folder.
The `tracer_prep_adv_states.py` is the one that is actually in use.

2026-08-24 12:54 UTC, OngChia commented on model/common/src/icon4py/model/common/config/config_io.py
> +def unstructure_reltime(reltime: time.RelativeTime) -> float:
In my test, the `dtime` is a float. I fixed the total integration time, and used maximum cfl number to compute the `dtime`. That is why I changed it to `float`.

2026-08-24 13:25 UTC, OngChia commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_vertical_tracer_advection.py
> +    return data_alloc.array_namespace(w).max(data_alloc.array_namespace(w).abs(w))
It seems no. I added `array_ns` as a local variable.

2026-08-24 20:51 UTC, OngChia commented on model/driver/tests/driver/scientific_validation/linear_tracer_advection_tests.py
> +# ICON4Py - ICON inspired code in Python and GT4Py
Good point. I agree that we should be consistent and use the **_tests naming convention.
I remember that convergence tests are usually categorized as verification tests. However, since the convergence tests are more computationally demanding, we currently mark them as validation tests. Do you think there would be a better way to categorize them, or is this distinction not really a concern here?

2026-08-26 06:20 UTC, jcanton commented
@OngChia small note on the torus grids: the fixture currently writes a NetCDF file and `GridManager` reads it back.

Correcting what I wrote here earlier — I had assumed the ICON schema mapping only existed inside the generator's private NetCDF writer, so that in-memory ingestion would need a translation layer. That's wrong. `IconGrid` already exposes all nine geometry fields under their exact ICON names, and all eight connectivities in `neighbor_tables` in icon4py's own convention (0-based, `-1` for missing, `int32`, entity-major), plus the global attributes and refinement control fields. The only differences from the on-disk form are degrees vs radians and packed `(n, 3)` cartesians — both trivial on our side.

What's missing is that none of this is documented or declared stable, so https://github.com/ofuhrer/icon-grid-generator/issues/6 now just asks for that (plus a couple of small fixes). Nothing there blocks us: domain decomposition, halo construction and derived neighbour tables belong to `GridManager` anyway, so the icon4py-side change is to let it take arrays as an alternative to a file path.

Keeping the file round-trip on this PR regardless — it costs ~0.02 s per grid, so nothing here is urgent.

🤖 Written by an agent on behalf of @jcanton

2026-09-02 23:12 UTC, OngChia commented on experiment_configs/linear_vertical_advection_box.yaml
> +geometry: {}
Agreed. Moved to `testing`

2026-09-02 23:13 UTC, OngChia commented on model/testing/src/icon4py/model/testing/config.py
> +)
Agreed! I removed the override support

2026-09-02 23:14 UTC, OngChia commented on model/testing/pyproject.toml
> +  "icon-grid-generator[netcdf]>=0.8.0",
As agreed in our discussion, I remove icon-grid-generator from this PR.

2026-09-02 23:19 UTC, OngChia commented on model/atmosphere/tracer_advection/src/icon4py/model/atmosphere/tracer_advection/tracer_advection_vertical.py
> +    Abstract base class for finite-volume vertical tracer advection schemes.
Not 100% sure here, but my understanding is that it still remains abstract because it declares abstract methods
```
@abc.abstractmethod
    def _compute_numerical_flux(

@abc.abstractmethod
    def _update_unknowns(
```

2026-09-03 11:47 UTC, msimberg commented on model/atmosphere/tracer_advection/src/icon4py/model/atmosphere/tracer_advection/tracer_advection_vertical.py
> +    Abstract base class for finite-volume vertical tracer advection schemes.
Ah yes, you're right. Sorry for the noise.

2026-09-03 12:19 UTC, msimberg commented on model/driver/tests/driver/validation_tests/test_tracer_advection_convergence.py
> +# ICON4Py - ICON inspired code in Python and GT4Py
In the end we might either just distinguish between verification and validation directly or have an independent axis which is "how heavy is this test to run" which is anyway the important part for deciding whether or not to run it in CI on every PR. Let's stick with validation for now?

However, can you check if validation_tests will now be included in test discovery in noxfile.py? I.e. do these tests actually end up running in the weekly CI?

2026-09-03 12:21 UTC, msimberg commented on model/driver/tests/driver/validation_tests/test_tracer_advection_convergence.py
> +    ).with_overrides(driver={"output_path": tmp_path / "ci_driver_output"})
I think you could at least put this logic in a helper function, if not in a test fixture.

2026-09-03 12:24 UTC, msimberg commented on model/common/src/icon4py/model/common/config/config_io.py
> +def unstructure_reltime(reltime: time.RelativeTime) -> float:
Hmm, would it not make more sense to cast to float where you use it if you need to have fractional times? If the times from the config are always integer seconds, then we should keep the type as int to keep that promise?

2026-09-03 12:24 UTC, msimberg reviewed
Looks very nice. Still a few minor questions.

2026-09-03 16:46 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-03 16:55 UTC, OngChia commented on model/driver/tests/driver/validation_tests/test_tracer_advection_convergence.py
> +    ).with_overrides(driver={"output_path": tmp_path / "ci_driver_output"})
I created `conftest.py` in `validation_tests` and put the fixture there, because I think that other scientific validation tests can also use this fixture in the future, and it will only be used by those tests.

2026-09-03 16:57 UTC, OngChia commented on model/driver/tests/driver/validation_tests/test_tracer_advection_convergence.py
> +# ICON4Py - ICON inspired code in Python and GT4Py
Totally agree with the point that "how heavy a test is". Okay. Let's stick with validation_tests.

2026-09-03 17:02 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBSETS=basic;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-03 17:26 UTC, OngChia commented on model/common/src/icon4py/model/common/config/config_io.py
> +def unstructure_reltime(reltime: time.RelativeTime) -> float:
I think times in the config should be allowed to be fractional. It just happens that most of the test cases use an integer time step. This is probably users are running simulations with grid spacings ~100 m to 100 km. If we run icon4py with dx=1 ~ 10 m, we may need to set the time step less than 1 s. 
Or should we let users to choose the unit, let's say millisecond?

2026-09-03 17:35 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBSETS=basic;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-03 17:39 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBSETS=basic;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-03 20:24 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBSETS=basic;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-04 20:00 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBSETS=basic;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-05 07:39 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBSETS=basic;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-05 08:06 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_gpu;LEVELS=validation;MODEL_SUBSETS=basic;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-05 17:49 UTC, OngChia commented on model/driver/tests/driver/validation_tests/test_tracer_advection_convergence.py
> +# ICON4Py - ICON inspired code in Python and GT4Py
I just ran cscs-ci default on back gpu and cpu backends. They both capture the tests and the tests pass. I assume the weekly CI will also capture the validation tests.

2026-09-08 18:18 UTC, OngChia commented on model/common/src/icon4py/model/common/config/config_io.py
> +def unstructure_reltime(reltime: time.RelativeTime) -> float:
So, following youe suggestion, I added unit to dtime so that users can specify seconds, milliseconds, or microseconds. dtime can be kept as an int as before.

2026-09-08 18:41 UTC, OngChia commented
cscs-ci run default;BACKENDS=gtfn_cpu;LEVELS=validation;MODEL_SUBSETS=basic;MODEL_SUBPACKAGES=driver;SESSIONS=model

2026-09-09 06:59 UTC, msimberg commented on model/common/tests/common/config/unit_tests/test_config_io.py
> +            "300 seconds\n...\n", time.RelativeTime, time.RelativeTime(seconds=300), id="reltime"
Nice, having the units there is a welcome addition!

2026-09-09 07:09 UTC, msimberg approved these changes

2026-09-11 07:31 UTC, OngChia commented on model/common/src/icon4py/model/common/initial_condition/analytical/linear_horizontal_tracer_advection.py
> +        origin_y=vertex_y.min(),
This is known. It will be tackled at next PR when I create parallel convergence tests.

2026-09-11 07:40 UTC, OngChia commented on model/driver/src/icon4py/model/driver/driver.py
> +        else None
No, it is not a problem. No initial conditions use prep_adv except the new convergence tests. If tracer is not turned on, the initial condition function for the convergence tests will throw an value error telling users that tracer advection should be turned on.

2026-09-11 07:41 UTC, OngChia commented on model/driver/tests/driver/mpi_tests/test_parallel_initial_conditions.py
> +        grid=single_rank_icon4py_driver.grid, allocator=allocator
This PR is for serial convergence tests. Parallel run will be tackled in the next PR.

2026-09-11 08:01 UTC, OngChia commented on model/atmosphere/tracer_advection/src/icon4py/model/atmosphere/tracer_advection/tracer_advection.py
> +            )
Again. This is not possible in this PR. But definitely need to be well tested in a subsequent PR.

2026-09-11 08:04 UTC, OngChia commented on model/common/src/icon4py/model/common/config/config_io.py
> +        return f"{int(seconds) * 1_000_000} microseconds"
Good catch!!

2026-09-11 09:10 UTC, OngChia commented on model/testing/src/icon4py/model/testing/config.py
> +)
Added

2026-09-11 10:34 UTC, merged