Metrics fields factory
C2SM/icon4py pull request #626
Opened 2024-12-12 09:40 UTC by nfarabullini

2024-12-12 10:04 UTC, nfarabullini commented
cscs-ci run default

2024-12-12 10:39 UTC, nfarabullini commented
cscs-ci run default

2024-12-12 10:48 UTC, nfarabullini commented
cscs-ci run default

2024-12-12 11:03 UTC, nfarabullini commented
cscs-ci run default

2024-12-12 14:39 UTC, nfarabullini commented
launch jenkins spack

2024-12-12 14:46 UTC, nfarabullini commented
cscs-ci run default

2024-12-12 14:46 UTC, nfarabullini commented
launch jenkins spack

2024-12-12 15:29 UTC, nfarabullini commented
cscs-ci run default

2024-12-13 07:49 UTC, nfarabullini commented
launch jenkins spack

2024-12-13 09:41 UTC, nfarabullini commented
cscs-ci run default

2024-12-13 11:01 UTC, nfarabullini commented
launch jenkins spack

2025-01-07 14:29 UTC, nfarabullini commented
cscs-ci run default

2025-01-07 14:31 UTC, nfarabullini commented
launch jenkins spack spackProject=C2SM/fix_testing_dependency

2025-01-07 15:49 UTC, nfarabullini commented
cscs-ci run default

2025-01-07 16:34 UTC, muellch commented
launch jenkins spack spackProject=C2SM/fix_testing_dependency

2025-01-14 12:35 UTC, nfarabullini commented
cscs-ci run default

2025-01-15 09:12 UTC, nfarabullini commented
cscs-ci run default

2025-01-15 12:06 UTC, nfarabullini commented
cscs-ci run default

2025-01-15 12:56 UTC, nfarabullini commented
cscs-ci run default

2025-01-16 12:03 UTC, halungge requested changes
looks much better. Still some cleanups that we can already do.

2025-01-16 12:03 UTC, halungge commented on model/common/src/icon4py/model/common/states/metadata.py
I think some of them are duplicated here and in the `metrics_attributes.py`I would suggest to keep only the ones in the `metrics_attributes.py` for the metrics field that you register in your factory .

2025-01-16 14:02 UTC, nfarabullini commented on model/common/tests/metric_tests/test_metric_fields.py
> +    exner_expol = 0.333 if experiment == dt_utils.REGIONAL_EXPERIMENT else 0.3333333333333
There is actually a difference between the 2

2025-01-16 14:39 UTC, nfarabullini commented
cscs-ci run default

2025-01-16 17:26 UTC, nfarabullini commented
cscs-ci run default

2025-01-20 08:00 UTC, nfarabullini commented
cscs-ci run default

2025-01-21 16:10 UTC, halungge reviewed
Mostly fixes for the metadata: 
   - remove duplicated entries in the metadata.py
   -  in the FieldMetaData for 1d fields there is sometimes the trailing comma missing for the 1d tuple.

2025-01-21 16:10 UTC, halungge commented on model/common/src/icon4py/model/common/states/factory.py
> +            dtype = metadata[next(iter(metadata))]["dtype"]
is this really necessary, or is it because of some duplicated entries in the metadata (maybe the ones from the geometry_attributes? Can you test that?

2025-01-22 14:26 UTC, nfarabullini commented on model/common/tests/metric_tests/test_metrics_factory.py
> +        (dt_utils.REGIONAL_EXPERIMENT, dt_utils.REGIONAL_EXPERIMENT),
that was my bad...sorry..

2025-01-22 14:28 UTC, nfarabullini commented on model/common/src/icon4py/model/common/metrics/metrics_factory.py
> +class MetricsConfig:
I use it here: https://github.com/C2SM/icon4py/blob/metrics_fields_factory/model/common/tests/metric_tests/test_metrics_factory.py#L37

Should I just transfer the code from the class to this function?

2025-01-22 14:52 UTC, nfarabullini commented on model/common/src/icon4py/model/common/metrics/metric_fields.py
> +@field_operator
I cannot do the latter as `_compute_exner_excfac` operations are only executed over a restricted domain but for the remaining cells, the `exner_exfac` is set to `exner_pol` . I'll do the first option

2025-01-22 15:03 UTC, nfarabullini commented on model/common/src/icon4py/model/common/metrics/compute_zdiff_gradp_dsl.py
> +    zdiff_gradp_full_field = data_alloc.flatten_first_two_dims(
flatten_first_two_dims also has assertions, which might be better as at least there is a check

2025-01-22 15:08 UTC, nfarabullini commented on model/common/src/icon4py/model/common/metrics/compute_zdiff_gradp_dsl.py
> +    zdiff_gradp_full_field = data_alloc.flatten_first_two_dims(
perhaps it might even be better to use `flatten_first_two_dims`in `compute_diffusion_metrics.py`

2025-01-23 10:13 UTC, nfarabullini commented
launch jenkins spack spackProject=C2SM/fix_testing_dependency

2025-01-23 10:25 UTC, nfarabullini commented
cscs-ci run default

2025-01-23 10:47 UTC, nfarabullini commented
launch jenkins spack spackProject=C2SM/fix_testing_dependency

2025-01-23 10:56 UTC, nfarabullini commented
cscs-ci run default

2025-01-23 11:56 UTC, nfarabullini commented
cscs-ci run default

2025-01-23 13:07 UTC, nfarabullini commented
cscs-ci run default

2025-01-23 14:14 UTC, merged